import { create } from 'zustand'
import type { SystemSettingsStore } from '~types'
import { DEFAULT_SYSTEM_SETTINGS_APPEARANCE } from './system-settings.constants'

const useSystemSettingsStore = create<SystemSettingsStore>((set) => ({
  ...DEFAULT_SYSTEM_SETTINGS_APPEARANCE,
  setAppearance: (appearance) => set({ appearance }),
  setColor: (color) => set({ color }),
  setTextHighlightColor: (textHighlightColor) => set({ textHighlightColor }),
  setSidebarIconSize: (sidebarIconSize) => set({ sidebarIconSize }),
  setWallpaperTint: (wallpaperTint) => set({ wallpaperTint }),
  setScrollBars: (scrollBars) => set({ scrollBars }),
  setScrollbarClick: (scrollbarClick) => set({ scrollbarClick }),
  setDockSize: (dockSize) => set({ dockSize }),
  setDockMagnification: (dockMagnification) => set({ dockMagnification }),
  setDockPosition: (dockPosition) => set({ dockPosition }),
  setMinimizeEffect: (minimizeEffect) => set({ minimizeEffect }),
  setDoubleClickTitleBarAction: (doubleClickTitleBarAction) => set({ doubleClickTitleBarAction }),
  setMinimizeWindowsIntoApplicationIcon: (minimizeWindowsIntoApplicationIcon) => set({ minimizeWindowsIntoApplicationIcon }),
  setAutoHideDock: (autoHideDock) => set({ autoHideDock }),
  setAnimateOpeningApplications: (animateOpeningApplications) => set({ animateOpeningApplications }),
  setShowIndicatorsForOpenApplications: (showIndicatorsForOpenApplications) => set({ showIndicatorsForOpenApplications }),
  setShowSuggestedAndRecentApplicationsInDock: (showSuggestedAndRecentApplicationsInDock) => set({ showSuggestedAndRecentApplicationsInDock }),
  setShowDesktopItemsOnDesktop: (showDesktopItemsOnDesktop) => set({ showDesktopItemsOnDesktop }),
  setShowDesktopItemsInStageManager: (showDesktopItemsInStageManager) => set({ showDesktopItemsInStageManager }),
  setWallpaperClickAction: (wallpaperClickAction) => set({ wallpaperClickAction }),
  setStageManager: (stageManager) => set({ stageManager }),
  setShowRecentAppsInStageManager: (showRecentAppsInStageManager) => set({ showRecentAppsInStageManager }),
  setStageManagerWindowDisplay: (stageManagerWindowDisplay) => set({ stageManagerWindowDisplay }),
  setShowWidgetsOnDesktop: (showWidgetsOnDesktop) => set({ showWidgetsOnDesktop }),
  setShowWidgetsInStageManager: (showWidgetsInStageManager) => set({ showWidgetsInStageManager }),
  setWidgetStyle: (widgetStyle) => set({ widgetStyle }),
  setUseIphoneWidgets: (useIphoneWidgets) => set({ useIphoneWidgets }),
  setDefaultWebBrowser: (defaultWebBrowser) => set({ defaultWebBrowser }),
  setDocumentTabsPreference: (documentTabsPreference) => set({ documentTabsPreference }),
  setAskToKeepChangesWhenClosingDocuments: (askToKeepChangesWhenClosingDocuments) => set({ askToKeepChangesWhenClosingDocuments }),
  setCloseWindowsWhenQuittingApplication: (closeWindowsWhenQuittingApplication) => set({ closeWindowsWhenQuittingApplication }),
  setTileWindowsByDraggingToScreenEdges: (tileWindowsByDraggingToScreenEdges) => set({ tileWindowsByDraggingToScreenEdges }),
  setTileWindowsByDraggingToMenuBar: (tileWindowsByDraggingToMenuBar) => set({ tileWindowsByDraggingToMenuBar }),
  setTileWindowsByHoldingOption: (tileWindowsByHoldingOption) => set({ tileWindowsByHoldingOption }),
  setTiledWindowsHaveMargins: (tiledWindowsHaveMargins) => set({ tiledWindowsHaveMargins }),
  setAutomaticallyRearrangeSpaces: (automaticallyRearrangeSpaces) => set({ automaticallyRearrangeSpaces }),
  setSwitchToSpaceWithOpenWindows: (switchToSpaceWithOpenWindows) => set({ switchToSpaceWithOpenWindows }),
  setGroupWindowsByApplication: (groupWindowsByApplication) => set({ groupWindowsByApplication }),
  setDisplaysHaveSeparateSpaces: (displaysHaveSeparateSpaces) => set({ displaysHaveSeparateSpaces }),
  setDragWindowsToTopForMissionControl: (dragWindowsToTopForMissionControl) => set({ dragWindowsToTopForMissionControl }),
}))

export default useSystemSettingsStore
