import type { LucideIcon } from 'lucide-react'
import {
  AppWindow,
  ArrowDownCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsRight,
  ChevronsUpDown,
  Clock,
  Cloud,
  CornerLeftUp,
  Columns3,
  Ellipsis,
  Disc3,
  FileText,
  Film,
  Folder,
  GalleryHorizontal,
  Globe,
  HardDrive,
  House,
  Image,
  Laptop,
  LayoutGrid,
  LayoutPanelTop,
  List,
  Network,
  PanelTop,
  Plus,
  Rows3,
  ScreenShare,
  Search,
  Server,
  Share,
  Tag,
  Usb,
  Wrench,
  X,
} from 'lucide-react'

export const seekerIcons = {
  airdrop: ScreenShare,
  aliasBadge: CornerLeftUp,
  applications: AppWindow,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronsRight: ChevronsRight,
  chevronsUpDown: ChevronsUpDown,
  close: X,
  clock: Clock,
  columns: Columns3,
  computer: Laptop,
  desktop: LayoutPanelTop,
  disc: Disc3,
  document: FileText,
  downloads: ArrowDownCircle,
  'external-disk': Usb,
  folder: Folder,
  gallery: GalleryHorizontal,
  globe: Globe,
  grid: LayoutGrid,
  group: Rows3,
  'hard-drive': HardDrive,
  home: House,
  'cloud-drive': Cloud,
  list: List,
  more: Ellipsis,
  movies: Film,
  music: PanelTop,
  network: Network,
  pictures: Image,
  plus: Plus,
  scss: FileText,
  search: Search,
  server: Server,
  share: Share,
  shared: Folder,
  tag: Tag,
  tsx: FileText,
  utilities: Wrench,
} satisfies Record<string, LucideIcon>
