import type { LucideIcon } from 'lucide-react'
import {
  AppWindow,
  ArrowDownCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Clock,
  Cloud,
  Columns3,
  Ellipsis,
  FileText,
  Film,
  Folder,
  GalleryHorizontal,
  House,
  Image,
  Laptop,
  LayoutGrid,
  LayoutPanelTop,
  List,
  Network,
  PanelTop,
  Plus,
  Rows3,
  ScreenShare,
  Search,
  Share,
  Tag,
  Wrench,
} from 'lucide-react'

export const seekerIcons = {
  airdrop: ScreenShare,
  applications: AppWindow,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  clock: Clock,
  columns: Columns3,
  computer: Laptop,
  desktop: LayoutPanelTop,
  document: FileText,
  downloads: ArrowDownCircle,
  folder: Folder,
  gallery: GalleryHorizontal,
  grid: LayoutGrid,
  group: Rows3,
  home: House,
  icloud: Cloud,
  list: List,
  more: Ellipsis,
  movies: Film,
  music: PanelTop,
  network: Network,
  pictures: Image,
  plus: Plus,
  scss: FileText,
  search: Search,
  share: Share,
  shared: Folder,
  tag: Tag,
  tsx: FileText,
  utilities: Wrench,
} satisfies Record<string, LucideIcon>
