const SEEKER_LIGHT_THEME = {
  '--seeker-header-focused': '#fdfdfd',
  '--seeker-header-unfocused': '#f2f2f2',
  '--seeker-header-title-focused': '#4c4c4c',
  '--seeker-header-title-unfocused': '#b0b0b0',
  '--seeker-tabbar-focused': '#f0f0f0',
  '--seeker-tabbar-unfocused': '#e3e3e3',
  '--seeker-tab-active-focused': '#fdfdfd',
  '--seeker-tab-active-unfocused': '#f2f2f2',
  '--seeker-tab-inactive-focused': '#f0f0f0',
  '--seeker-tab-inactive-focused-hover': '#e3e3e3',
  '--seeker-tab-inactive-unfocused': '#e3e3e3',
  '--seeker-tab-inactive-unfocused-hover': '#d6d6d6',
  '--seeker-tab-add-focused': '#f0f0f0',
  '--seeker-tab-add-focused-hover': '#e3e3e3',
  '--seeker-tab-add-focused-active': '#cac9c9',
  '--seeker-tab-add-unfocused': '#e3e3e3',
  '--seeker-tab-add-unfocused-hover': '#d6d6d6',
  '--seeker-tab-active-text-focused': '#2f2f2f',
  '--seeker-tab-active-text-unfocused': '#a0a0a0',
  '--seeker-tab-inactive-text-focused': '#2f2f2f',
  '--seeker-tab-inactive-text-unfocused': '#a0a0a0',
  '--seeker-tab-add-icon-focused': '#6b6b6b',
  '--seeker-tab-add-icon-unfocused': '#a8a8a8',
  '--seeker-tab-divider-focused': '#dedede',
  '--seeker-tab-divider-unfocused': '#d1d1d1',
  '--seeker-tabbar-top-inner-shadow-focused': 'inset 0 1px 0 0 rgba(205, 205, 205, 0.45), inset 0 2px 0 0 rgba(221, 221, 221, 0.22), inset 0 3px 0 0 rgba(240, 240, 240, 0)',
  '--seeker-tabbar-top-inner-shadow-unfocused': 'inset 0 1px 0 0 rgba(191, 191, 191, 0.45), inset 0 2px 0 0 rgba(211, 211, 211, 0.22), inset 0 3px 0 0 rgba(227, 227, 227, 0)',
  '--seeker-tab-close-hover-active-tab': '#e3e2e2',
  '--seeker-tab-close-active-active-tab': '#d5d4d5',
  '--seeker-tab-close-hover-inactive-tab': '#b5b4b4',
  '--seeker-tab-close-active-inactive-tab': '#8a8989',
  '--seeker-tab-close-icon-focused': '#808080',
  '--seeker-tab-close-icon-hover-focused': '#666666',
  '--seeker-tab-close-icon-active-focused': '#595959',
  '--seeker-tab-close-icon-unfocused': '#b8b8b8',
  '--seeker-tab-close-icon-hover-unfocused': '#9a9a9a',
  '--seeker-tab-close-icon-active-unfocused': '#878787',
  '--seeker-list-row-light': '#ffffff',
  '--seeker-list-row-dark': '#f4f5f5',
  '--seeker-list-name-text': '#3b3b3d',
  '--seeker-list-metadata-text': '#858585',
  '--seeker-list-selected-unfocused': '#dcdbdc',
  '--seeker-tab-bottom-border': '#d9d9d9',
  '--seeker-list-header-bottom-border': '#f0f0f0',
} as const

const SEEKER_DARK_THEME = {
  '--seeker-header-focused': '#363636',
  '--seeker-header-unfocused': '#282828',
  '--seeker-header-title-focused': '#eaeaea',
  '--seeker-header-title-unfocused': '#696969',
  '--seeker-tabbar-focused': '#1e1e1e',
  '--seeker-tabbar-unfocused': '#2e2e2e',
  '--seeker-tab-active-focused': '#363636',
  '--seeker-tab-active-unfocused': '#282828',
  '--seeker-tab-inactive-focused': '#1e1e1e',
  '--seeker-tab-inactive-focused-hover': '#2e2e2e',
  '--seeker-tab-inactive-unfocused': '#161616',
  '--seeker-tab-inactive-unfocused-hover': '#222222',
  '--seeker-tab-add-focused': '#1e1e1e',
  '--seeker-tab-add-focused-hover': '#2e2e2e',
  '--seeker-tab-add-focused-active': '#343434',
  '--seeker-tab-add-unfocused': '#161616',
  '--seeker-tab-add-unfocused-hover': '#222222',
  '--seeker-tab-active-text-focused': '#ffffff',
  '--seeker-tab-active-text-unfocused': '#696969',
  '--seeker-tab-inactive-text-focused': '#9a9a9a',
  '--seeker-tab-inactive-text-unfocused': '#575757',
  '--seeker-tab-add-icon-focused': '#9a9a9a',
  '--seeker-tab-add-icon-unfocused': '#575757',
  '--seeker-tab-divider-focused': '#474747',
  '--seeker-tab-divider-unfocused': '#393939',
  '--seeker-tabbar-top-inner-shadow-focused': 'inset 0 1px 0 0 #000000',
  '--seeker-tabbar-top-inner-shadow-unfocused': 'inset 0 1px 0 0 #000000',
  '--seeker-tab-close-hover-active-tab': '#595959',
  '--seeker-tab-close-active-active-tab': '#777777',
  '--seeker-tab-close-hover-inactive-tab': '#595959',
  '--seeker-tab-close-active-inactive-tab': '#777777',
  '--seeker-tab-close-icon-focused': '#adadad',
  '--seeker-tab-close-icon-hover-focused': '#adadad',
  '--seeker-tab-close-icon-active-focused': '#ffffff',
  '--seeker-tab-close-icon-unfocused': '#adadad',
  '--seeker-tab-close-icon-hover-unfocused': '#adadad',
  '--seeker-tab-close-icon-active-unfocused': '#ffffff',
  '--seeker-list-row-light': '#1e1e1e',
  '--seeker-list-row-dark': '#292929',
  '--seeker-list-name-text': '#ffffff',
  '--seeker-list-metadata-text': '#858585',
  '--seeker-list-selected-unfocused': '#454546',
  '--seeker-tab-bottom-border': '#000000',
  '--seeker-list-header-bottom-border': '#2d2d2d',
} as const

export function applySeekerTheme(element: HTMLElement, isDarkMode: boolean) {
  const theme = isDarkMode ? SEEKER_DARK_THEME : SEEKER_LIGHT_THEME

  for (const [name, value] of Object.entries(theme)) {
    element.style.setProperty(name, value)
  }
}
