const SYSTEM_SETTINGS_LIGHT_THEME = {
  '--system-settings-sidebar-focused': 'rgba(208, 204, 205, 0.68)',
  '--system-settings-sidebar-unfocused': '#f2f2f2',
  '--system-settings-sidebar-border': 'rgba(191, 191, 191, 0.58)',
  '--system-settings-sidebar-search-icon': '#5f5f5f',
  '--system-settings-sidebar-search-border': '#bdbdbd',
  '--system-settings-sidebar-search-bg': 'rgba(201, 201, 201, 0.5)',
  '--system-settings-sidebar-search-placeholder': '#8b8b8b',
  '--system-settings-sidebar-item-text': '#1f1f1f',
  '--system-settings-sidebar-selected-focused': '#ec72b1',
  '--system-settings-sidebar-selected-unfocused': '#d8d8d8',
  '--system-settings-sidebar-selected-unfocused-text': '#6e6e6e',
  '--system-settings-sidebar-category-icon-bg': '#1f1f1f',
  '--system-settings-row-label': '#1f1f1f',
  '--system-settings-accent-swatch-selected-border': '#ffffff',
  '--system-settings-accent-swatch-ring': '#9a9a9a',
  '--system-settings-accent-swatch-border': 'rgba(0, 0, 0, 0.11)',
  '--system-settings-appearance-tile-selected-border': '#ef5ba1',
  '--system-settings-appearance-tile-shadow': 'rgba(0, 0, 0, 0.15)',
  '--system-settings-appearance-label-selected': '#1f1f1f',
  '--system-settings-appearance-label': '#555555',
  '--system-settings-help-shadow': 'rgba(0, 0, 0, 0.11)',
  '--system-settings-preview-light-frame': '#ececee',
  '--system-settings-preview-light-sidebar': '#d9d9dc',
  '--system-settings-preview-light-content': '#ffffff',
  '--system-settings-preview-light-title': '#ef5ba1',
  '--system-settings-preview-light-header': '#e9e9eb',
  '--system-settings-preview-light-line-primary': '#cacacd',
  '--system-settings-preview-light-line-secondary': '#d8d8db',
  '--system-settings-preview-dark-frame': '#232426',
  '--system-settings-preview-dark-sidebar': '#303236',
  '--system-settings-preview-dark-content': '#191a1d',
  '--system-settings-preview-dark-title': '#12c7d6',
  '--system-settings-preview-dark-header': '#2b2d31',
  '--system-settings-preview-dark-line-primary': '#56585d',
  '--system-settings-preview-dark-line-secondary': '#45474c',
  '--system-settings-preview-muted-light': 'rgba(255, 255, 255, 0.8)',
  '--system-settings-preview-muted-dark': 'rgba(255, 255, 255, 0.28)',
} as const

const SYSTEM_SETTINGS_DARK_THEME = {
  '--system-settings-sidebar-focused': 'rgba(44, 44, 46, 0.78)',
  '--system-settings-sidebar-unfocused': '#252527',
  '--system-settings-sidebar-border': 'rgba(255, 255, 255, 0.14)',
  '--system-settings-sidebar-search-icon': '#a0a0a5',
  '--system-settings-sidebar-search-border': '#555557',
  '--system-settings-sidebar-search-bg': 'rgba(255, 255, 255, 0.1)',
  '--system-settings-sidebar-search-placeholder': '#8e8e93',
  '--system-settings-sidebar-item-text': '#f5f5f7',
  '--system-settings-sidebar-selected-focused': '#ec72b1',
  '--system-settings-sidebar-selected-unfocused': '#3a3a3c',
  '--system-settings-sidebar-selected-unfocused-text': '#a0a0a5',
  '--system-settings-sidebar-category-icon-bg': '#1f1f1f',
  '--system-settings-row-label': '#f5f5f7',
  '--system-settings-accent-swatch-selected-border': '#ffffff',
  '--system-settings-accent-swatch-ring': '#8e8e93',
  '--system-settings-accent-swatch-border': 'rgba(255, 255, 255, 0.16)',
  '--system-settings-appearance-tile-selected-border': '#ef5ba1',
  '--system-settings-appearance-tile-shadow': 'rgba(0, 0, 0, 0.28)',
  '--system-settings-appearance-label-selected': '#f5f5f7',
  '--system-settings-appearance-label': '#a0a0a5',
  '--system-settings-help-shadow': 'rgba(0, 0, 0, 0.28)',
  '--system-settings-preview-light-frame': '#ececee',
  '--system-settings-preview-light-sidebar': '#d9d9dc',
  '--system-settings-preview-light-content': '#ffffff',
  '--system-settings-preview-light-title': '#ef5ba1',
  '--system-settings-preview-light-header': '#e9e9eb',
  '--system-settings-preview-light-line-primary': '#cacacd',
  '--system-settings-preview-light-line-secondary': '#d8d8db',
  '--system-settings-preview-dark-frame': '#232426',
  '--system-settings-preview-dark-sidebar': '#303236',
  '--system-settings-preview-dark-content': '#191a1d',
  '--system-settings-preview-dark-title': '#12c7d6',
  '--system-settings-preview-dark-header': '#2b2d31',
  '--system-settings-preview-dark-line-primary': '#56585d',
  '--system-settings-preview-dark-line-secondary': '#45474c',
  '--system-settings-preview-muted-light': 'rgba(255, 255, 255, 0.8)',
  '--system-settings-preview-muted-dark': 'rgba(255, 255, 255, 0.28)',
} as const

export function applySystemSettingsTheme(element: HTMLElement, isDarkMode: boolean) {
  const theme = isDarkMode ? SYSTEM_SETTINGS_DARK_THEME : SYSTEM_SETTINGS_LIGHT_THEME

  for (const [name, value] of Object.entries(theme)) {
    element.style.setProperty(name, value)
  }
}
